---
kind: pipeline
type: docker
name: default

steps:

  - name: home  
    image: plugins/home
    settings:
      repo: quadeare/resume
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: ${DRONE_BRANCH}