---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Cheezecake home"
subtitle: "Cheezecake"
logo: "assets/logo.png"

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
#message:
#  style: "is-warning"
#  title: "Optional message!"
#  content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque risus mi, tempus quis placerat ut, porta nec nulla. Vestibulum rhoncus ac ex sit amet fringilla. Nullam gravida purus diam, et dictum felis venenatis efficitur. Aenean ac eleifend lacus, in mollis lectus. Donec sodales, arcu et sollicitudin porttitor, tortor urna tempor ligula."

# Optional navbar
links:
  - name: ""
    icon: ""
    url: ""

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Partage"
    icon: "fas fa-folder-open"
    items:
      - name: "Plex"
        logo: "/assets/tools/plex.png"
        subtitle: "Plateforme de streaming"
        tag: "streaming"
        url: "https://plex.cheezecake.ovh/"
      - name: "Nextcloud"
        logo: "/assets/tools/nextcloud.png"
        subtitle: "Hébergement de fichier et travail collaboratif"
        url: "https://nextcloud.cheezecake.ovh/"
        tag: "sharing"
      - name: "Seafile"
        logo: "/assets/tools/seafile.png"
        subtitle: "Hébergement de fichier et travail collaboratif"
        tag: "sharing"
        url: "https://seafile.cheezecake.ovh/"
      - name: "Ubooquity"
        logo: "/assets/tools/ubooquity.png"
        subtitle: "Serveur de BDs et Ebooks"
        tag: "streaming"
        url: "https://ebook.cheezecake.ovh/"
  - name: "Téléchargemnt"
    icon: "fas fa-skull-crossbones"
    items:
      - name: "Rutorrent"
        logo: "/assets/tools/rutorrent.png"
        subtitle: "Téléchargement de torrent en ligne"
        tag: "download"
        url: "https://dl.cheezecake.ovh/"
      - name: "Sonarr"
        logo: "/assets/tools/tv.png"
        subtitle: "Téléchargement automatique de séries TV"
        tag: "download"
        url: "https://tv.cheezecake.ovh/"
      - name: "Radarr"
        logo: "/assets/tools/movie.png"
        subtitle: "Téléchargement automatique de films"
        tag: "download"
        url: "https://movie.cheezecake.ovh/"
      - name: "Lidarr"
        logo: "/assets/tools/music.png"
        subtitle: "Téléchargement automatique de musique"
        tag: "download"
        url: "https://music.cheezecake.ovh/"
      - name: "Jackett"
        logo: "/assets/tools/jackett.png"
        subtitle: "API de centralisation de tackers"
        tag: "download"
        url: "https://jackett.cheezecake.ovh/"
  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Bitwarden"
        logo: "/assets/tools/bitwarden.png"
        subtitle: "Gestionnaire de mot de passe"
        tag: "tools"
        url: "https://pass.cheezecake.ovh/"
      - name: "Keycloak"
        logo: "/assets/tools/keycloak.png"
        subtitle: "Gestionnaire de compte"
        tag: "sso"
        url: "https://sso.cheezecake.ovh/"
      - name: "Rancher"
        logo: "/assets/tools/rancher.png"
        subtitle: "Plateforme de supervision Kubernetes"
        tag: "k8s"
        url: "https://rancher.cheezecake.ovh/"